spring:
  datasource:
    follow:
      jdbc-url: jdbc:mysql://192.168.1.148:3306/test_dayi_follow?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: dayi
      password: dayiSpot@)!%0905
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: FollowHikariPool
    dayi:
      jdbc-url: jdbc:mysql://192.168.1.148:3306/test_storage_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: dayi
      password: dayiSpot@)!%0905
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: DayiHikariPool
  session:
    store-type: hash_map

dayi:
  mq:
    nameservAddr: 192.168.1.148:9876
    consumerGroup: dayi-follow-consumer-test
  component:
    constant: #常量参数
      properties:
        imageHost: http://localhost:9601
        financeHost: https://teststorage.dayi35.com/finance
  dataBase: test_storage_spot
follow:
  dataBase: test_dayi_follow
