spring:
  datasource:
    url: jdbc:mysql://192.168.1.148:3306/dayi_wms_all?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: dayi
    password: dayiSpot@)!%0905
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 500
      pool-name: HikariPool
  session:
    #store-type: redis
    store-type: hash_map
  redis:
    database: 1
    #host: 172.28.1.53
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 20000
    pool:
      max-active: 500
      max-wait: 5000
      max-idle: 50
      min-idle: 10

dubbo:
  registry:
    address: zookeeper://192.168.1.148:2181
    username:
    password:
  application:
    name: dayi-wms
    owner: dayi
    organization: dayi
  protocol:
    dubbo:
      port: 21510
  threads: 500
  timeout: 10000

dayi:
  mq:
    nameservAddr: 192.168.1.148:9876
    producerGroup: dayi-wms-producer
    consumerGroup: dayi-wms-consumer
  component:
    constant: #常量参数
      ucHost: https://teststorageuc.dayi35.com
