spring:
  datasource:
    follow:
      jdbc-url: jdbc:mysql://172.28.1.3:3306/inet_dayi_follow?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      password: monda43%-346ujNyu7deJ
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: FollowHikariPool
    dayi:
      jdbc-url: jdbc:mysql://172.28.1.3:3306/inet_dayi_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      password: monda43%-346ujNyu7deJ
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: DayiHikariPool
  session:
    store-type: hash_map

dubbo:
  registry:
    address: zookeeper://172.28.1.63:2181
    username:
    password:
  application:
    name: dayi-follow
    owner: dayi
    organization: dayi
  protocol:
    dubbo:
      port: 21510
  threads: 100
  timeout: 10000

dayi:
  mq:
    nameservAddr: 172.28.1.63:9876
    consumerGroup: dayi-follow-consumer-inet
  component:
    constant: #常量参数
      properties:
        imageHost: http://localhost:9601
        financeHost: http://jr.fiidee.inet
  dataBase: inet_dayi_spot
follow:
  dataBase: inet_dayi_follow
