spring:
  datasource:
    follow:
      jdbc-url: jdbc:mysql://172.28.1.3:3306/inet_dayi_follow?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      password: monda43%-346ujNyu7deJ
      driver-class-name: com.mysql.jdbc.Driver
    dayi:
      jdbc-url: jdbc:mysql://172.28.1.3:3306/inet_dayi_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      password: monda43%-346ujNyu7deJ
      driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: HikariPool
  session:
    store-type: hash_map

dayi:
  mq:
    nameservAddr: 172.28.1.63:9876
    consumerGroup: dayi-follow-consumer
  component:
    constant: #常量参数
      properties:
        imageHost: http://localhost:9601
  dataBase: inet_dayi_spot
follow:
  dataBase: inet_dayi_follow
