spring:
  datasource:
    follow:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dayi_follow?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: finance
      password: monda123
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: FollowHikariPool
    dayi:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dayi_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: finance
      password: monda123
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: DayiHikariPool
  session:
    store-type: hash_map

dayi:
  mq:
    nameservAddr: 172.28.1.61:9876
    consumerGroup: dayi-follow-consumer
  component:
    constant: #常量参数
      properties:
        imageHost: http://localhost:9601
  dataBase: dayi_spot
follow:
  dataBase: dayi_follow
