server:
  port: 9601
  tomcat:
    max-threads: 500
    min-spare-threads: 20
  session:
    cookie:
      max-age: 1800

spring:
  profiles:
    active: ${profile.active}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: -1
  redis:
    password: 1234
    cluster:
      nodes: 192.168.15.128:7001, 192.168.15.128:7002, 192.168.15.129:7001, 192.168.15.129:7002, 192.168.15.130:7001, 192.168.15.130:7002

dayi:
  serverid: 160
  component:
    constant: #常量参数
      properties:
        version: ${random.int[1024,65536]}
    captcha:
      char-length: 4
      char-string: 34578acdefhkmpvwxy


