# fiancneuc 配置文件
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dayi_wms_all?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: monda123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          minimum-idle: 5
          maximum-pool-size: 100
          pool-name: HikariPool
  session:
    store-type: hash_map
  redis:
        database: 1
        #host: 172.28.1.53
        host: 127.0.0.1
        port: 6379
        password: 123456
        timeout: 20000
        pool:
          max-active: 100
          max-wait: -1
          max-idle: 10
          min-idle: 0

dubbo:
  registry:
    address: zookeeper://172.28.1.61:2181
    username:
    password:
  application:
    name: dayi-wms
    owner: dayi
    organization: dayi
  protocol:
    dubbo:
      port: 21510
  threads: 100
  timeout: 10000
dayi:
  mq:
    nameservAddr: 172.28.1.61:9876
    producerGroup: dayi-wms-producer
    consumerGroup: dayi-wms-consumer
  component:
    constant: #常量参数
      ucHost: http://financeuc.fiidee.loc
#  component:
#    constant: #常量参数
#      properties:
#        imagesDomain: http://localhost:8080