spring:
  datasource:
    follow:
      jdbc-url: jdbc:mysql://192.168.1.58:3386/dayi_follow?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: dayi
      password: dayiSpot@)!%0905
      driver-class-name: com.mysql.jdbc.Driver
    dayi:
      jdbc-url: jdbc:mysql://192.168.1.58:3386/dayi_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: dayi
      password: dayiSpot@)!%0905
      driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: HikariPool
  session:
    store-type: hash_map

dayi:
  mq:
    nameservAddr: 192.168.1.133:9876
    consumerGroup: dayi-follow-consumer
  component:
    constant: #常量参数
      properties:
        imageHost: http://localhost:9601
  dataBase: dayi_spot
follow:
  dataBase: dayi_follow
