server:
  port: 9601
  tomcat:
    max-threads: 500
    min-spare-threads: 20

spring:
  profiles:
    active: ${profile.active}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: -1

mybatis:
  mapper-locations: classpath:com/dayi/user/manager/**/mapper/*.xml

dayi:
  serverid: 160
  component:
    constant: #常量参数
      properties:
        version: ${random.int[1024,65536]}
    captcha:
      char-length: 4
      char-string: 34578acdefhkmpvwxy

