server:
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    follow:
      #jdbc-url: jdbc:mysql://172.28.1.3:3306/dayi_follow_all?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dayi_follow_all?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      #password: monda43%-346ujNyu7deJ
      password: monda123
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: FollowHikariPool
    dayi:
      #jdbc-url: jdbc:mysql://172.28.1.3:3306/dev_dayi_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      jdbc-url: jdbc:mysql://127.0.0.1:3306/dev_dayi_spot?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      username: root
      #password: monda43%-346ujNyu7deJ
      password: monda123
      driver-class-name: com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 200
      pool-name: DayiHikariPool
  session:
    store-type: hash_map

dubbo:
  registry:
    address: zookeeper://172.28.1.60:2181
    username:
    password:
  application:
    name: dayi-follow
    owner: dayi
    organization: dayi
  threads: 100
  timeout: 10000

dayi:
  mq:
    nameservAddr: 172.28.1.60:9876
    consumerGroup: dayi-follow-consumer
  component:
    constant: #常量参数
      properties:
        imageHost: http://localhost:9601
        financeHost: http://localhost:8080/finance
  dataBase: dev_dayi_spot
follow:
  dataBase: dayi_follow_all
