spring:
  datasource:
    url: jdbc:mysql://172.28.1.3:3306/inet_wms_all?useUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: monda43%-346ujNyu7deJ
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      pool-name: HikariPool

  session:
    #store-type: redis
    store-type: hash_map
  redis:
        database: 1
        host: 172.28.1.55
        #host: 127.0.0.1
        port: 6379
        password: 123456
        timeout: 20000
        pool:
          max-active: 100
          max-wait: -1
          max-idle: 10
          min-idle: 0

dubbo:
  registry:
    address: zookeeper://172.28.1.63:2181
    username:
    password:
  application:
    name: dayi-wms
    owner: dayi
    organization: dayi
  protocol:
    dubbo:
      port: 21510
  threads: 100
  timeout: 10000

dayi:
  mq:
    nameservAddr: 172.28.1.63:9876
    producerGroup: dayi-wms-producer
    consumerGroup: dayi-wms-consumer
  component:
      constant: #常量参数
        ucHost: http://user.fiidee.inet
