server:
  port: 8080

spring:
  profiles:
    active: ${profile.active}
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: -1
  mvc:
    view:
      prefix:/WEB-INF/views/
      suffix:.jsp




